import { ApolloServerErrorCode } from "@apollo/server/errors";

export enum ApolloServerErrorCodeExtended {
  INTERNAL_SERVER_ERROR = ApolloServerErrorCode.INTERNAL_SERVER_ERROR,
  GRAPHQL_PARSE_FAILED = ApolloServerErrorCode.GRAPHQL_PARSE_FAILED,
  GRAPHQL_VALIDATION_FAILED = ApolloServerErrorCode.GRAPHQL_VALIDATION_FAILED,
  PERSISTED_QUERY_NOT_FOUND = ApolloServerErrorCode.PERSISTED_QUERY_NOT_FOUND,
  PERSISTED_QUERY_NOT_SUPPORTED = ApolloServerErrorCode.PERSISTED_QUERY_NOT_SUPPORTED,
  BAD_USER_INPUT = ApolloServerErrorCode.BAD_USER_INPUT,
  OPERATION_RESOLUTION_FAILURE = ApolloServerErrorCode.OPERATION_RESOLUTION_FAILURE,
  BAD_REQUEST = ApolloServerErrorCode.BAD_REQUEST,
}
